#!/bin/bash
echo $PWD
for file in $PWD/input/*.xml; do
	[ -e "$file" ] || continue
	echo $cleanFile 
	xsltproc "$PWD/transform.xsl" "${file}" > "${file}.clean"
	xmllint -format "${file}.clean"
	diff "${file}" "${file}.clean" > "${file}.log"
done
